language: python

python:
  - 3.9

install:
  - pip install -r requirements.txt

script:
  - python3 manage.py || python manage.py
  - black --check .
  - flake8 .
  - coverage run manage.py test

after_script:
  - coveralls