language: python

python:
  - 3.9

install:
  - pip install -r requirements.txt

before-script:
  - python manage.py migrate

script:
  - black --check .
  - flake8 .
  - coverage run manage.py test

after_script:
  - coveralls