language: python

python:
  - 3.9

install:
  - pip install -r requirements.txt


script:
  - black --check .
  - flake8 .
  - python manage.py migrate
  - coverage run manage.py test

after_script:
  - coveralls